### ISSUE TITLE
Change encoding of object values to match encoding of array values

### ISSUE THREAD

**Issue by go-oleg** [juttle/pluggable-json#5]
While working on https://github.com/juttle/pluggable-json/pull/4, I realized we could simplify the code by encoding values in objects the same way we encode values in arrays.

Currently, when encoding a value in an object, we stash the serializer type into the key.

```
{
  "time": new Date(0)
}
// becomes
{
  "time:date": "1970-01-01T00:00:00.000Z"
}
```

whereas in an array,

```
[ new Date(0) ]
// becomes
[ "date:1970-01-01T00:00:00.000Z"]
```

We could instead stash the serializer type into the value in the object case as well:

```
{
  "time": new Date(0)
}
// will become
{
  "time": "date:1970-01-01T00:00:00.000Z"
}
```

Potential downsides:
- Slightly decreased readibility. Keys are typically shorter and only have `[A-z]` so the separator and type stick out better compared to being in the `value`.
- May want to switch the default separator (`":"`) to something else, since it occurs in JavaScript Date serialization which is one of the common usecases of PluggableJSON. More generally, values typically have a greater variety of characters than keys.

I don't think either of these are particularly major.

@demmer thoughts?

**Comment by demmer** [comment]
I think the consistency gained by always encoding the value outweighs the potential downsides so I'd support this rework.

I do agree that continuing to use a single `:` as the separator isn't ideal. What about something like:

```
{
  "time": "$date$1970-01-01T00:00:00.000Z"
}
```

In other words, the encoding would be `<sigil><type><sigil><value>`, and we would use `$` as the default sigil.

Visually this stands out more and seems less likely to occur in practice.

**Comment by go-oleg** [comment]
@demmer, thx for the feedback. I like the sigil at the beginning (and middle) approach...it does make it a lot easier to see what is and isn't encoded.
